### ISSUE TITLE
Enhance home view

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#23]
- Add the sound icon near the checkbox to on/off the sound of paddles.
 
![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/40ac28d6-e3ab-4bdc-8daf-ccf5b328e4e2)
![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/71120ca3-3b20-45d2-ac68-3139aecef756)

- Add "exit" option to exit the game (close the window tab)

**Comment by ujjwxl** [comment]
working on this issue

**Comment by Ramzi-Abidi** [comment]
> working on this issue

Nice, I assigned it to you!
