### ISSUE TITLE
Adding confirmation when user clicks return to menu during gameplay

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#33]
When the user clicks on 'return to menu,' we should display a SweetAlert to inform them.

The alert should ask:

'Want to exit the gameplay?' with 'Yes' and 'Cancel' options.

'Yes': redirect the user to the home page.

'Cancel': remove the alert from the DOM.

Link to SweetAlert1: https://sweetalert.js.org/guides/#getting-started"

PS: If you find an alert from sweetAlert1 better than the one bellow, don't hesitate to use it.

Screenshot example:
![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/16fdbf16-98c6-4557-ab36-be24f8e7c2e0)

**Comment by ujjwxl** [comment]
working on it
