### ISSUE TITLE
Play a sound once a player scores a goal.

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#36]
When one of the players score a goal we should play a sound.

Explanation:

- In the two main components singlePlayerMode and multiPlayerMode exactly in the piece of code shown bellow:

![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/b8588c43-75db-4a63-8d25-29491fb02986)

before resetting the game we can play a sound like this one [sound](https://www.youtube.com/watch?v=ZITqCczx84s)

**Comment by remiBoudreau** [comment]
Hey @Ramzi-Abidi mind if I take this?

**Comment by Ramzi-Abidi** [comment]
@remiBoudreau absolutely!

**Comment by remiBoudreau** [comment]
@Ramzi-Abidi Great! I see you merged already! Happy to help!

**Comment by Ramzi-Abidi** [comment]
@remiBoudreau Yes I checked your PR on my local machine and you solved the issue perfectly.

Thanks! More issues are coming, and your future PRs are welcome. If you like the project, give it a star please!

**Comment by remiBoudreau** [comment]
Glad to hear it!
