### ISSUE TITLE
Add 3 radio buttons (slow, medium, fast) when user enter settings 

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#43]
When the user clicks on "Settings," three radio buttons will be displayed:

Slow
Medium
Fast

If "Fast" is chosen, we will increase a little bit the "x" and "y" velocities of the ball.

If "Medium" is chosen, we will maintain the initial values.

If "Slow" is chosen, we will decrease the velocity of the ball and paddles.

To avoid hardcoding the velocity values for paddles and the ball, it is recommended to put them in a separate file.

We can utilize [MUI-radio-buttons](https://mui.com/material-ui/react-radio-button/) for the user interface.

**Comment by aditya4196** [comment]
@Ramzi-Abidi Can you assign this issue to me?

**Comment by Ramzi-Abidi** [comment]
> @Ramzi-Abidi Can you assign this issue to me?

@aditya4196  Sure !
