### ISSUE TITLE
Add sound when user clicks on any button

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#44]
Just like any game, we aim to immerse the user in a gaming experience.

When the user clicks on any button, we want to enhance the interaction by triggering a corresponding sound effect.

For this purpose, consider using a sound file such as [click-sound](https://www.youtube.com/watch?v=eckk-vXJbJ4)

**Comment by ujjwxl** [comment]
Working on it!
