### ISSUE TITLE
Ad icons in menu section in home view

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#46]
Use the **icons** bellow in the menu of home view as mentioned in the screenshot:

![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/933daa1a-3b04-484a-8c25-380a5792c2f5)

- Single player: [Single-players](https://www.flaticon.com/free-icon/person_9743387?term=one+player&page=1&position=1&origin=search&related_id=9743387)

- Settings: [Settings](https://www.flaticon.com/free-icon/cogwheel_3953226?term=settings&page=1&position=10&origin=search&related_id=3953226)

- Two player: [Two-players](https://www.flaticon.com/free-icon/people_9743498?term=two+players&page=1&position=1&origin=search&related_id=9743498)

**Comment by ujjwxl** [comment]
Working on it!

**Comment by Ramzi-Abidi** [comment]
> Working on it!

Ok, nice!
