### ISSUE TITLE
Add a rule in the initial popup when launching the game.

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#62]
Add this rule text in the two-player component:
- The winner is the player who reaches a score of 10

![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/683ff85e-e723-4763-b7f3-db52e6022abd)

**Comment by ujjwxl** [comment]
Working on it!

**Comment by Ramzi-Abidi** [comment]
@ujjwxl Ok!
