### ISSUE TITLE
Add rules in the initial popup when launching a game in singe mode

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#63]
Add these two rules in single-mode component:

- Game is over when the score reaches 10.
- Prepare to face a tough BOT! Let's see how long you can stand against it.

![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/0651fef0-1e5e-442e-916b-4df085419659)

**Comment by rennacarver** [comment]
Getting some practice in with Github pull requests. Would love to give this issue a try~

**Comment by Ramzi-Abidi** [comment]
> Getting some practice in with Github pull requests. Would love to give this issue a try~

Sounds great @rennacarver, feel free to work on it!
