### ISSUE TITLE
Add menu button to feedback alert/popup when game is over

### ISSUE THREAD

**Issue by Ramzi-Abidi** [Ramzi-Abidi/Pong#64]
Add button to navigate user to "/" route when game is over in both **single** and **two-players** modes.

![image](https://github.com/Ramzi-Abidi/Pong/assets/69228547/7f5963bf-0391-4078-af7e-29705baeb34b)

**Comment by ujjwxl** [comment]
Working on it!

**Comment by Ramzi-Abidi** [comment]
> Working on it!

Ok, nice!!
